version: "2"
services:
  coachbase:
    image: couchbase:community-6.6.0
    restart: "no"
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    volumes:
      - "./couchbase:/opt/couchbase/var"
#  keycloak:
#    image: quay.io/keycloak/keycloak:12.0.2
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: Pa55w0rd
#    ports:
#      - 8080:8080
